### ISSUE TITLE
Login and Sign-Up

### ISSUE THREAD

**Issue by mentorcreed** [Allen-ISD-Computer-Science/REPO_WorkoutProgress_2024#22]
The website won't allow me to sign up or log in because my password doesn't adhere to the requirements, even though my password does meet the requirements.

**Comment by Matthew-Roman** [comment]
We don't have an account system yet. As a matter in fact none of us here know how to set one up, don't let this halt your progress. Sadly this is an issue for another time, focus on the sites pages and design.

**Comment by Matthew-Roman** [comment]
I will close this now as not as planned, you can fix it but I wouldn't worry about the functionality of this specific feature until we as a group collectively start the backend of the site.
